#! /usr/bin/env bash

# Entrypoint to create a user, and run command as that user. This allows us
# to pass BUILD_UID and BUILD_GID environment variables at container run-time
# to not clobber the permissions and ownership of mounted volumes

USERNAME="vamp"

cat /etc/motd

if [[ -z $BUILD_UID ]] ; then
  exec $@
else
  [[ -z $BUILD_GID ]] && BUILD_GID="$BUILD_UID"

  echo "Adding user inside docker container:" \
       "uid=${BUILD_UID}($USERNAME) gid=${BUILD_GID}($USERNAME)"

  groupadd --gid "$BUILD_GID" "$USERNAME" \
    && useradd --uid "$BUILD_UID" --gid "$BUILD_GID" "$USERNAME" \
    || { echo "Failed to add user, exiting!"; exit 1; }

  exec su "$USERNAME" --command="$*"
fi
