#! /usr/bin/env bash

# Entrypoint to create a user, and run command as that user. This allows us
# to pass BUILD_UID and BUILD_GID environment variables at container run-time
# to not clobber the permissions and ownership of mounted volumes

USERNAME="vamp"

if [[ -z $BUILD_UID ]] ; then
  echo "No BUILD_UID set, spawning shell"
  exec /bin/bash -l
fi

if [[ -z $BUILD_GID ]] ; then
  echo "BUILD_GID is empty, using '$BUILD_UID'"
  BUILD_GID="$BUILD_UID"
fi

if [[ ! $( id "$BUILD_UID" 2> /dev/null ) ]] ; then
  groupadd --gid "$BUILD_GID" "$USERNAME"
  useradd --uid "$BUILD_UID" --gid "$BUILD_GID" "$USERNAME"
fi

cat /etc/motd

if [[ $# -ge 1 ]] ; then
  exec su "$USERNAME" --command="$*"
else
  echo "No command specified, exiting!"
fi

