#! /usr/bin/env bash

# SBT launcher: http://www.scala-sbt.org/0.13/docs/Manual-Installation.html

: "${SBT_LAUNCH:=/usr/local/bin/sbt-launch.jar}"

java \
  -Xms512M \
  -Xmx1536M \
  -Xss1M \
  -XX:+CMSClassUnloadingEnabled \
  -jar "$SBT_LAUNCH" \
  "$@"
